CLASSES_NAMES = [
    "background",  # class 0
    "aeroplane",  # class 1
    "bicycle",  # class 2
    "bird",  # class 3
    "boat",  # class 4
    "bottle",  # class 5
    "bus",  # class 6
    "car",  # class 7
    "cat",  # class 8
    "chair",  # class 9
    "cow",  # class 10
    "table",  # class 11
    "dog",  # class 12
    "horse",  # class 13
    "motorbike",  # class 14
    "person",  # class 15
    "pottedplant",  # class 16
    "sheep",  # class 17
    "sofa",  # class 18
    "train",  # class 19
    "tvmonitor",  # class 20
    "bag",  # class 21
    "bed",  # class 22
    "bench",  # class 23
    "book",  # class 24
    "building",  # class 25
    "cabinet",  # class 26
    "ceiling",  # class 27
    "cloth",  # class 28
    "computer",  # class 29
    "cup",  # class 30
    "door",  # class 31
    "fence",  # class 32
    "floor",  # class 33
    "flower",  # class 34
    "food",  # class 35
    "grass",  # class 36
    "ground",  # class 37
    "keyboard",  # class 38
    "light",  # class 39
    "mountain",  # class 40
    "mouse",  # class 41
    "curtain",  # class 42
    "platform",  # class 43
    "sign",  # class 44
    "plate",  # class 45
    "road",  # class 46
    "rock",  # class 47
    "shelves",  # class 48
    "sidewalk",  # class 49
    "sky",  # class 50
    "snow",  # class 51
    "bedclothes",  # class 52
    "track",  # class 53
    "tree",  # class 54
    "truck",  # class 55
    "wall",  # class 56
    "water",  # class 57
    "window",  # class 58
    "wood",  # class 59
]
